#!/bin/bash
mkdir "$1 at $(date)"
cd "$1 at $(date)"

mkdir about_me
cd about_me
mkdir personal
cd personal
touch facebook.txt
echo "https://www.facebook.com/$2" > facebook.txt
cd ..
mkdir professional
cd professional
touch linkedin.txt
echo "https://www.linkedin.com/$3" > linkedin.txt
cd ..
cd ..

mkdir my_friends
cd my_friends
touch list_of_my_friends.txt
curl https://gist.githubusercontent.com/tegarimansyah/e91f335753ab2c7fb12815779677e914/raw/94864388379fecee450fde26e3e73bfb2bcda194/list%2520of%2520my%2520friends.txt -o list_of_my_friends.txt
cd ..
mkdir my_system_info
cd my_system_info

touch about_this_laptop.txt
cat << EOF > about_this_laptop.txt
My username: $USER
With host: uname -a
EOF

touch internet_connection.txt
cat << EOF > internet_connection.txt
Connection to google: 
$(ping -c 3 forcesafesearch.google.com)
EOF

echo halo dunia

sudo chmod +x automate
./automate sultan zarfin.lasut sultan-fariz