// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	orders "Pinjem/businesses/orders"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DomainRepository is an autogenerated mock type for the DomainRepository type
type DomainRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, domain
func (_m *DomainRepository) Create(ctx context.Context, domain orders.Domain) (orders.Domain, error) {
	ret := _m.Called(ctx, domain)

	var r0 orders.Domain
	if rf, ok := ret.Get(0).(func(context.Context, orders.Domain) orders.Domain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(orders.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, orders.Domain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *DomainRepository) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *DomainRepository) GetAll(ctx context.Context) ([]orders.Domain, error) {
	ret := _m.Called(ctx)

	var r0 []orders.Domain
	if rf, ok := ret.Get(0).(func(context.Context) []orders.Domain); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]orders.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *DomainRepository) GetById(ctx context.Context, id uint) (orders.Domain, error) {
	ret := _m.Called(ctx, id)

	var r0 orders.Domain
	if rf, ok := ret.Get(0).(func(context.Context, uint) orders.Domain); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(orders.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrdersByUserId provides a mock function with given fields: ctx, userId
func (_m *DomainRepository) GetOrdersByUserId(ctx context.Context, userId uint) ([]orders.Domain, error) {
	ret := _m.Called(ctx, userId)

	var r0 []orders.Domain
	if rf, ok := ret.Get(0).(func(context.Context, uint) []orders.Domain); ok {
		r0 = rf(ctx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]orders.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *DomainRepository) UpdateStatus(ctx context.Context, id uint, status bool) (orders.Domain, error) {
	ret := _m.Called(ctx, id, status)

	var r0 orders.Domain
	if rf, ok := ret.Get(0).(func(context.Context, uint, bool) orders.Domain); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Get(0).(orders.Domain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uint, bool) error); ok {
		r1 = rf(ctx, id, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
