name: "unit test golang"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  unit-test:
    name: "do unit test to project"
    runs-on: ubuntu-latest
    steps:
      - name: "setup github action (CI)"
        uses: actions/checkout@v2
      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: run unit test
        uses: go test ./... -cover

  build-push-docker:
    name: "build and push docker image to registry"
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: "setup github action (CI)"
      - uses: actions/checkout@v2
        run: docker build -t sultanfariz/pinjem:1.0.0 .
